from __future__ import annotations

import json
import re
from typing import Any


REQUIRED_DEFAULTS = {
    "product_id_type": "EAN",
    "sales_form": "single",
    "quantity": 100,
    "condition_type": "new_new",
    "shipping_channel": "FBM",
}


def generate_dianxiaomi_attributes(
    *,
    llm_client,
    listing: dict[str, Any],
    product_context: str = "",
    marketplace: str = "US",
) -> dict[str, Any]:
    """把已生成的 Listing 转成店小秘表单 JSON。"""
    normalized_listing = _normalize_listing(listing)
    if not normalized_listing["title"]:
        raise ValueError("Listing 标题不能为空")

    content = llm_client.generate(
        _system_prompt(),
        _user_prompt(
            listing=normalized_listing,
            product_context=product_context,
            marketplace=marketplace,
        ),
    )
    attrs = _parse_json_object(content)
    return _normalize_attributes(attrs, normalized_listing)


def _system_prompt() -> str:
    return (
        "You are a JSON adapter for Dianxiaomi Amazon listing forms. "
        "只输出合法 JSON，不要输出 markdown 或解释。不要重写 Listing；title、bullet_points、"
        "description、search_terms 必须基于用户提供的 Listing 原文。"
        "不要编造价格、品牌、颜色、尺寸、重量等事实；上下文没有提供就使用空字符串或 null。"
    )


def _user_prompt(*, listing: dict[str, Any], product_context: str, marketplace: str) -> str:
    return (
        f"Marketplace: {marketplace or 'US'}\n"
        f"Product context:\n{product_context or ''}\n\n"
        "Listing generated by my agent:\n"
        f"{json.dumps(listing, ensure_ascii=False, indent=2)}\n\n"
        "Return JSON with these fields: title, product_identifier, product_id_type, brand, "
        "manufacturer, sales_form, color, description, bullet_points, standard_price, quantity, "
        "condition_type, product_type, item_keywords, search_terms, shipping_channel, "
        "package_length, package_width, package_height, package_weight, image_urls."
    )


def _parse_json_object(content: str) -> dict[str, Any]:
    cleaned = re.sub(r"<think>.*?</think>", "", content or "", flags=re.DOTALL).strip()
    cleaned = re.sub(r"<think\s*/>", "", cleaned).strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```\w*\n?", "", cleaned)
        cleaned = re.sub(r"\n?```$", "", cleaned).strip()
    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise ValueError(f"店小秘 JSON 解析失败: {exc}") from exc
    if not isinstance(parsed, dict):
        raise ValueError("店小秘 JSON 必须是对象")
    return parsed


def _normalize_listing(listing: dict[str, Any]) -> dict[str, Any]:
    bullets = listing.get("bullet_points") or listing.get("bullets") or []
    if not isinstance(bullets, list):
        bullets = []
    search_terms = listing.get("search_terms")
    if not search_terms and isinstance(listing.get("backend_terms"), list):
        search_terms = " ".join(str(term) for term in listing["backend_terms"])
    return {
        "title": _clean_text(listing.get("title")),
        "bullet_points": [_clean_text(item) for item in bullets if _clean_text(item)][:5],
        "description": _clean_text(listing.get("description")),
        "search_terms": _clean_text(search_terms),
    }


def _normalize_attributes(attrs: dict[str, Any], listing: dict[str, Any]) -> dict[str, Any]:
    output = dict(attrs)
    output.update(REQUIRED_DEFAULTS | {key: output.get(key) for key in output.keys()})
    output["title"] = listing["title"][:200]
    output["description"] = listing["description"][:1990]
    output["search_terms"] = listing["search_terms"][:250]
    bullets = list(listing["bullet_points"])
    output["bullet_points"] = (bullets + [""] * 5)[:5]
    output["manufacturer"] = _clean_text(output.get("manufacturer")) or _clean_text(output.get("brand"))
    output["product_identifier"] = _clean_text(output.get("product_identifier")) or listing["title"][:50]
    output["brand"] = _clean_text(output.get("brand"))
    output["color"] = _clean_text(output.get("color"))
    output["product_type"] = _clean_text(output.get("product_type"))
    output["item_keywords"] = _clean_text(output.get("item_keywords"))
    if output.get("standard_price") in ("", "null"):
        output["standard_price"] = None
    if not isinstance(output.get("image_urls"), list):
        output["image_urls"] = []
    return output


def _clean_text(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()

